"""Constants package for VIIRS SCAGDRFS."""
from .paths import (
    TOPDIR,
    PETALIB_DIR,
    PETALIB_STAGING_DIR,
    VJ109GA_NRT_DIR,
    WORK_DIR,
)
from .products import (
    LANCE_CONCEPT_ID_VJ1,
    LANCE_CONCEPT_ID_VNP,
    PRODUCT_SHORT_NAME_VJ1,
    PRODUCT_SHORT_NAME_VNP,
    LOCK_TIMEOUT,
    MAX_RETRIES,
    TARGET_GROUP_ID,
    FILE_PERMISSIONS,
    DIR_PERMISSIONS,
)

from .field_info import (
    VALID_FIELD_NAMES,
    FIELD_BITDEPTHS,
    DTYPE_FOR_BITDEPTH,
)

__all__ = [
    "TOPDIR",
    "PETALIB_DIR",
    "PETALIB_STAGING_DIR",
    "VJ109GA_NRT_DIR",
    "WORK_DIR",
    "LANCE_CONCEPT_ID_VJ1",
    "LANCE_CONCEPT_ID_VNP",
    "PRODUCT_SHORT_NAME_VJ1",
    "PRODUCT_SHORT_NAME_VNP",
    "LOCK_TIMEOUT",
    "MAX_RETRIES",
    "TARGET_GROUP_ID",
    "FILE_PERMISSIONS",
    "DIR_PERMISSIONS",
    "VALID_FIELD_NAMES",
    "FIELD_BITDEPTHS",
    "DTYPE_FOR_BITDEPTH",
]
