"""Constants package for VIIRS SCAGDRFS."""

from .paths import (
    TOPDIR,
    PETALIB_DIR,
    PETALIB_STAGING_DIR,
    WORK_DIR,
    WATER_MASK_DIR,
    DRFS_COMPONENT_DIR,
    get_nrt_dir,
)
from .products import (
    SUPPORTED_PRODUCTS,
    PRODUCT_LANCE_CONFIG,
    PRODUCT_SENSOR,
    PRODUCT_TIF_PATTERN,
    LANCE_CONCEPT_ID_MOD_NRT,
    LANCE_CONCEPT_ID_VJ1_NRT,
    LANCE_CONCEPT_ID_VNP_NRT,
    PRODUCT_SHORT_NAME_MOD_NRT,
    PRODUCT_SHORT_NAME_VJ1_NRT,
    PRODUCT_SHORT_NAME_VNP_NRT,
    LOCK_TIMEOUT,
    MAX_RETRIES,
    TARGET_GROUP_ID,
    FILE_PERMISSIONS,
    DIR_PERMISSIONS,
)

from .field_info import (
    VALID_FIELD_NAMES,
    FIELD_BITDEPTHS,
    DTYPE_FOR_BITDEPTH,
)

__all__ = [
    "TOPDIR",
    "PETALIB_DIR",
    "PETALIB_STAGING_DIR",
    "WORK_DIR",
    "WATER_MASK_DIR",
    "DRFS_COMPONENT_DIR",
    "get_nrt_dir",
    # products
    "SUPPORTED_PRODUCTS",
    "PRODUCT_LANCE_CONFIG",
    "PRODUCT_SENSOR",
    "PRODUCT_TIF_PATTERN",
    "LANCE_CONCEPT_ID_MOD",
    "LANCE_CONCEPT_ID_VJ1",
    "LANCE_CONCEPT_ID_VNP",
    "PRODUCT_SHORT_NAME_MOD",
    "PRODUCT_SHORT_NAME_VJ1",
    "PRODUCT_SHORT_NAME_VNP",
    "LOCK_TIMEOUT",
    "MAX_RETRIES",
    "TARGET_GROUP_ID",
    "FILE_PERMISSIONS",
    "DIR_PERMISSIONS",
    # field_info
    "VALID_FIELD_NAMES",
    "FIELD_BITDEPTHS",
    "DTYPE_FOR_BITDEPTH",
]
