[FILE_INFO]
WATER_MASK_REGEX=MOD44W.A2000055.%s.006.2009*.water_pcent.bin
BIP_SUFFIX=.bip
BIP_META_SUFFIX=.bip.meta
SOLAR_AZIMUTH_SUFFIX=.SolarAzimuth_1.dat
SOLAR_ZENITH_SUFFIX=.SolarZenith_1.dat
DELTA_VIS_SUFFIX=.deltavis.cleanse.dat
GRAIN_SIZE_SUFFIX=.drfs.grnsz.cleanse.dat
FORCING_SUFFIX=.forcing.cleanse.dat
SCAGDRFS_VERSION=V01.1
DELTA_VIS_UNMASKED=VIRSCGDRF_NRT_DELTAVIS_%s_VNP09GANRT061_%s_%s.bin.Unmask
GRAIN_SIZE_UNMASKED=VIRSCGDRF_NRT_drfsGS_%s_VNP09GANRT061_%s_%s.bin.Unmask
FORCING_UNMASKED=VIRSCGDRF_NRT_RF_%s_VNP09GANRT061_%s_%s.bin.Unmask
DELTA_VIS_OUTFILE=VIRSCGDRF_NRT_DELTAVIS_%s_VNP09GANRT061_%s_%s.bin.mask
GRAIN_SIZE_OUTFILE=VIRSCGDRF_NRT_drfsGS_%s_VNP09GANRT061_%s_%s.bin.mask
FORCING_OUTFILE=VIRSCGDRF_NRT_RF_%s_VNP09GANRT061_%s_%s.bin.mask
# The following are used to glob for files.
# The %s entries are replaced in the strings.
# Use glob, not regex for TIF_VERSIONS
UNMASKED_TIF_BASENAME=VIRSCGDRF_NRT%s%s_VNP09GANRT061_%s_%s.Unmask.tif
MASKED_TIF_BASENAME=VIRSCGDRF_NRT%s%s_VNP09GANRT061_%s_%s.tif
TIF_VERSIONS=V01.?
DRFS_DELTAVIS_PART=_DELTAVIS_
DRFS_DRFSGS_PART=_drfsGS_
DRFS_RF_PART=_RF_
SCAG_GS_PART=_GS_
SCAG_ICE_PART=_ICE_
SCAG_ROCK_PART=_ROCK_
SCAG_SHADE_PART=_SHADE_
SCAG_SNOW_PART=_SNOW_
SCAG_VEG_PART=_VEG_
NC_BASENAME=VIRSCGDRF_NRT_%s_VNP09GANRT061_%s_%s.nc
