import datetime as dt
import subprocess
from pathlib import Path

import click

import shutil
from src.constants.paths import WORK_DIR, TOPDIR, get_slurm_scratch
from src.mask_scag import mask_scag
from src.constants.products import SUPPORTED_PRODUCTS, PRODUCT_FILE_EXTENSION
from src.constants.paths import WORK_DIR, TOPDIR
from src.util import get_date_from_filename, get_info_from_bip_file
from concurrent.futures import ThreadPoolExecutor

import logging
from src.log_config import setup_logging

logger = logging.getLogger(__name__)


@click.command()
@click.option(
    "-b",
    "--bip-file",
    type=click.Path(file_okay=True, dir_okay=False, exists=True, path_type=Path),
    help="Band Interleaved by Pixel (BIP) file to process.",
)
@click.option(
    "-h",
    "--src-file",
    type=click.Path(file_okay=True, dir_okay=False, exists=True, path_type=Path),
    help="H5 or HDF file to process.",
)
@click.option(
    "--product",
    "-P",
    type=click.Choice(SUPPORTED_PRODUCTS, case_sensitive=False),
    required=True,
    help="Input product to process (MOD09GA, VNP09GA, VJ109GA).",
)
@click.option(
    "-w",
    "--working-dir",
    type=click.Path(
        file_okay=False, dir_okay=True, writable=True, exists=False, path_type=Path
    ),
    envvar="SLURM_SCRATCH",
    default=lambda: WORK_DIR,
    show_default=True,
    help="Path to working directory where intermediate files are stored. "
    "Defaults to environment variable WORK_DIR. Date and tile ID subdirectories"
    " will be added (e.g. 2023.10.03/h08v04).",
)
def run_scag(bip_file, src_file, working_dir, product):

    # TODO: Get this list of control files from a template and ancillary directory
    control_files = list(working_dir.glob("**/*.control"))

    # $PM/scag_code/bin/scag MOD09GA.A2023244.h08v05.061.NRT.bip 7 2400 2400 $fil
    # scag_code/bin/scag BIP-file num-bands num-samples num-lines control-file
    # Usage: scag [OPTION...] IMGFILE NBANDS NSAMPLES NLINES CONTROLFILE
    bip_info = get_info_from_bip_file(bip_file.with_suffix(bip_file.suffix + ".meta"))

    def run_command(cmd):
        result_str = ""
        start_time = dt.datetime.now()
        result_str += f"starting run_command() at {dt.datetime.now()}: {cmd}"
        result = subprocess.run(
            cmd, shell=True, capture_output=True, text=True, executable="/usr/bin/bash"
        )
        end_time = dt.datetime.now()
        result.check_returncode()
        result_str += f"stdout\n{result.stdout.rstrip()}\n"
        result_str += f"stderr\n{result.stderr.rstrip()}\n"
        result_str += f"  done run_command() at {dt.datetime.now()}: {cmd}"
        run_time = end_time - start_time
        result_str += f"  Processing time {run_time} for {cmd}"

        return result_str

    ext = PRODUCT_FILE_EXTENSION[product.upper()]
    cmds = [
        f"cd {working_dir}; {TOPDIR}/scag_code/bin/scag {bip_file.name} "
        f"{bip_info['num_bands']} {bip_info['num_samples']} "
        f"{bip_info['num_lines']} {control_file.name}"
        for control_file in control_files
    ]
    logger.info("Running %d scag invocations", len(cmds))
    with ThreadPoolExecutor(max_workers=5) as pool:
        results = list(pool.map(run_command, cmds))

    for result in results:
        logger.info("SCAG command result:\n%s", result)

    # TODO: Get this list of .pic files -- which are generated by `scag` executable -- from a template
    local_src = working_dir / src_file.name
    cmd_sort = (
        f"cd {working_dir}; {TOPDIR}/scag_code/bin/scag_sort "
        f"2eminput 3eminput modprty2 modprty3 "
        f"{str(local_src).replace(f'{ext}', '.')} "
        f"{bip_info['num_samples']} {bip_info['num_lines']}"
    )
    scag_sort_starttime = dt.datetime.now()
    result_sort = subprocess.run(
        cmd_sort, shell=True, capture_output=True, text=True, executable="/usr/bin/bash"
    )
    scag_sort_endtime = dt.datetime.now()
    result_sort.check_returncode()
    scag_sort_str = ""
    scag_sort_str += f"\n\nscag sort cmd:\n{cmd_sort}\n"
    scag_sort_str += f"scag sort took: {scag_sort_endtime - scag_sort_starttime}\n"
    scag_sort_str += f"scag sort stdout: {result_sort.stdout.rstrip()}\n"
    scag_sort_str += f"scag sort stderr: {result_sort.stderr.rstrip()}\n"
    logger.info("SCAG sort command result:\n%s", scag_sort_str)

    date = get_date_from_filename(src_file)
    tile = bip_info["tile_id"]
    # mask scag and create geotifs
    logger.info(f"Starting mask_scag")
    mask_scag(
        date=date,
        working_dir=working_dir,
        tile=tile,
        product=product,
    )
    logger.info(f"...finished mask_scag")

    # node-local scratch is purged at job end — copy results out
    og_working_dir = WORK_DIR / product.upper() / date.strftime("%Y.%m.%d") / tile
    og_working_dir.mkdir(parents=True, exist_ok=True)

    tifs = list(working_dir.glob("**/*.tif"))
    if not tifs:
        raise RuntimeError(f"mask_scag produced no tifs in {working_dir}")
    for src in tifs:
        shutil.copy2(src, og_working_dir / src.name)
    logger.info("Copied %d tifs to %s", len(tifs), og_working_dir)


if __name__ == "__main__":
    """Executed from the command line"""
    setup_logging(level=logging.DEBUG)
    run_scag()
