import datetime as dt
import subprocess
from pathlib import Path

import click
from dask.distributed import Client
from dask_jobqueue import SLURMCluster

from src.mask_scag import mask_scag
from src.constants.products import SUPPORTED_PRODUCTS, PRODUCT_FILE_EXTENSION
from src.constants.paths import WORK_DIR, TOPDIR
from src.util import get_date_from_filename, get_info_from_bip_file


# TODO: This function is not used:  setup_scag_cluster()
def setup_scag_cluster():
    # NOTE: account "ucb544_peak2" is set to expire Aug 7, 2026
    print(f"Setting up scag_cluster at {dt.datetime.now()}")
    cluster = SLURMCluster(
        shebang="#!/usr/bin/bash",
        account="ucb544_peak2",
        cores=1,
        memory="10GB",
        walltime="01:00:00",
        local_directory=str(WORK_DIR / "dask"),
        job_extra_directives=[
            "--qos=normal",
            "--job-name=scag-proc",
            "--partition=amilan",
        ],
        log_directory=str(WORK_DIR / "dask" / "jobqueue-logs"),
    )
    # cluster.adapt(minimum_jobs=1, maximum_jobs=50)
    # This should be 30 so that all 30 pic files can be created at once
    cluster.scale(30)

    return cluster


@click.command()
@click.option(
    "-b",
    "--bip-file",
    type=click.Path(file_okay=True, dir_okay=False, exists=True, path_type=Path),
    help="Band Interleaved by Pixel (BIP) file to process.",
)
@click.option(
    "-h",
    "--src-file",
    type=click.Path(file_okay=True, dir_okay=False, exists=True, path_type=Path),
    help="H5 or HDF file to process.",
)
@click.option(
    "--product",
    "-P",
    type=click.Choice(SUPPORTED_PRODUCTS, case_sensitive=False),
    required=True,
    help="Input product to process (MOD09GA, VNP09GA, VJ109GA).",
)
@click.option(
    "-w",
    "--working-dir",
    type=click.Path(
        file_okay=False, dir_okay=True, writable=True, exists=False, path_type=Path
    ),
    default=lambda: WORK_DIR,
    show_default=True,
    help="Path to working directory where intermediate files are stored. "
    "Defaults to environment variable WORK_DIR. Date and tile ID subdirectories"
    " will be added (e.g. 2023.10.03/h08v04).",
)
def run_scag(bip_file, src_file, working_dir, product):

    scag_cluster = setup_scag_cluster()
    scag_client = Client(scag_cluster)

    # TODO: Get this list of control files from a template and ancillary directory
    control_files = list(working_dir.glob("**/*.control"))

    # $PM/scag/bin/scag MOD09GA.A2023244.h08v05.061.NRT.bip 7 2400 2400 $fil
    # scag/bin/scag BIP-file num-bands num-samples num-lines control-file
    # Usage: scag [OPTION...] IMGFILE NBANDS NSAMPLES NLINES CONTROLFILE
    bip_info = get_info_from_bip_file(bip_file.with_suffix(bip_file.suffix + ".meta"))

    def run_command(cmd):
        result_str = ""
        start_time = dt.datetime.now()
        result_str += f"starting run_command() at {dt.datetime.now()}: {cmd}"
        result = subprocess.run(
            cmd, shell=True, capture_output=True, text=True, executable="/usr/bin/bash"
        )
        end_time = dt.datetime.now()
        result.check_returncode()
        result_str += f"stdout\n{result.stdout}"
        result_str += f"stderr\n{result.stderr}"
        result_str += f"  done run_command() at {dt.datetime.now()}: {cmd}"
        run_time = end_time - start_time
        result_str += f"  Processing time {run_time} for {cmd}"

        return result_str

    ext = PRODUCT_FILE_EXTENSION[product.upper()]
    delayed_tasks = []
    for control_file in control_files:
        cmd = f"cd {working_dir}; {TOPDIR}/scag/bin/scag {bip_file.name} {bip_info['num_bands']} {bip_info['num_samples']} {bip_info['num_lines']} {control_file.name}"
        print(f"  submitting delayed task for {control_file=} at {dt.datetime.now()}")
        delayed_task = scag_client.submit(run_command, cmd)
        print(f"  appending delayed task for {control_file=} at {dt.datetime.now()}")
        delayed_tasks.append(delayed_task)

    print(f"About to gather scag_client.... {dt.datetime.now()}", flush=True)
    results = scag_client.gather(delayed_tasks)
    print(f"  ...Finished gathering scag_client.... {dt.datetime.now()}")

    for result in results:
        print("SCAG command result: ", result, "\n")

    # TODO: Get this list of .pic files -- which are generated by `scag` executable -- from a template
    cmd_sort = f"cd {working_dir}; {TOPDIR}/scag/bin/scag_sort 2eminput 3eminput modprty2 modprty3 {str(src_file).replace(f'{ext}', '.')} {bip_info['num_samples']} {bip_info['num_lines']}"
    scag_sort_starttime = dt.datetime.now()
    result_sort = subprocess.run(
        cmd_sort, shell=True, capture_output=True, text=True, executable="/usr/bin/bash"
    )
    scag_sort_endtime = dt.datetime.now()
    result_sort.check_returncode()
    scag_sort_str = ""
    scag_sort_str += f"\n\nscag sort cmd:\n{cmd_sort}\n"
    scag_sort_str += f"scag sort took:\n{scag_sort_endtime - scag_sort_starttime}\n"
    scag_sort_str += f"scag sort stdout:\n{result_sort.stdout}\n"
    scag_sort_str += f"scag sort stderr:\n{result_sort.stderr}\n"
    print("SCAG sort command result: ", scag_sort_str, "\n")

    # mask scag and create geotifs
    print(f"Starting mask_scag at {dt.datetime.now()}")
    mask_scag(
        date=get_date_from_filename(src_file),
        working_dir=working_dir,
        tile=bip_info["tile_id"],
        product=product,
    )
    print(f"  ...finished mask_scag at {dt.datetime.now()}")


if __name__ == "__main__":
    """Executed from the command line"""
    run_scag()
